language: ruby
rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0

sudo: false

gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.1.gemfile

jobs:
  exclude:
  - gemfile: gemfiles/rails_6.0.1.gemfile
    rvm: 2.3.0
  - gemfile: gemfiles/rails_6.0.1.gemfile
    rvm: 2.4.0